METAR_EXPECTATIONS = [

  { raw: 'EGGW 091450Z 21013KT CAVOK 10/06 Q1031',
    parsed:
    { type: 'METAR',
      station: 'EGGW',
      time: Time.strptime('091450+0000', '%d%H%M%z'),
      auto: false,
      correction: false,
      wind: { variation: nil, direction: 210, variable: false, speed: 13, unit: 'KT' },
      cavok: true,
      visibility: nil,
      runway_visual_range: nil,
      weather: nil,
      clouds: nil,
      temperature: { temperature: 10, dewpoint: 6 },
      altimeter: { hpa: 1031 },
      recent_weather: nil,
      windshear: nil,
      non_standard: nil
    },
    readable: 'EGGW. Dec 9, 14:50 UTC. Wind of 13KT at 210 degrees. Clear sky. Temperature 10 degrees. Dew point 6 degrees. Pressure altitude 1031 hpa.'
  },

  { raw: 'METAR EFJY 171950Z AUTO CCA 27006KT 220V310 9999 R36/1000V2400FT/U +BLSN VCSH FEW012 SCT015 BKN060 13/12 Q1006 REFZRA WS RWY36',
    parsed:
      { type: 'METAR',
        station: 'EFJY',
        time: Time.strptime('171950+0000', '%d%H%M%z'),
        auto: true,
        correction: 'A',
        wind:   { speed: 6,
                  direction: 270,
                  variable: true,
                  variation: { min: 220, max: 310 },
                  unit: 'KT' },
        cavok: false,
        visibility: { distance: '9999', unit: 'meters' },
        runway_visual_range: { runway: '36', direction: nil, minIndicator: nil, minValue: '1000', maxIndicator: nil, maxValue: '2400', unit: 'FT', trend: 'upward' },
        weather: ['heavy intensity blowing snow', 'in the vicinity showers'],
        clouds:   [{ type: 'few',
                     altitude: 1200,
                     cumulonimbus: false,
                     towering_cumulus: false },
                   { type: 'scattered',
                     altitude: 1500,
                     cumulonimbus: false,
                     towering_cumulus: false },
                   { type: 'broken',
                     altitude: 6000,
                     cumulonimbus: false,
                     towering_cumulus: false }],
        recent_weather: 'Freezing Rain',
        temperature: { temperature: 13, dewpoint: 12 },
        windshear: 'runway 36',
        altimeter: { hpa: 1006 },
        non_standard: nil
    },
    readable: 'EFJY (autostation). Correction #A. Dec 17, 19:50 UTC. Variable (from 220 to 310 degrees) wind of 6KT at 270 degrees. Visibility 9999 meters. Temperature 13 degrees. Dew point 12 degrees. Pressure altitude 1006 hpa. Visual range for runway #36 is varying from 1000 to 2400 FT, the trend is upward. Weather : heavy intensity blowing snow, in the vicinity showers. Few clouds at 1200 feets, scattered clouds at 1500 feets, broken clouds at 6000 feets. Freezing Rain. Windshear was encountered on runway 36.'
  },

  { raw: 'SPECI EGGW 151750Z 14012KPH 6000 RA BKN003 OVC004 10/10 Q1014',
    parsed:
      { type: 'SPECI',
        station: 'EGGW',
        time: Time.strptime('151750+0000', '%d%H%M%z'),
        auto: false,
        correction: false,
        wind:   { speed: 12, direction: 140, variable: false, variation: nil, unit: 'KPH' },
        cavok: false,
        visibility: { distance: '6000', unit: 'meters' },
        runway_visual_range: nil,
        weather: ['rain'],
        clouds:   [{ type: 'broken',
                     altitude: 300,
                     cumulonimbus: false,
                     towering_cumulus: false },
                   { type: 'overcast',
                     altitude: 400,
                     cumulonimbus: false,
                     towering_cumulus: false }],
        recent_weather: nil,
        temperature: { temperature: 10, dewpoint: 10 },
        windshear: nil,
        altimeter: { hpa: 1014 },
        non_standard: nil
      },
    readable: 'EGGW. Dec 15, 17:50 UTC. Wind of 12KPH at 140 degrees. Visibility 6000 meters. Temperature 10 degrees. Dew point 10 degrees. Pressure altitude 1014 hpa. Weather : rain. Broken clouds at 300 feets, overcast clouds at 400 feets.'
  },

  { raw: 'EHLW 151755Z AUTO 11011KT 060V150 4000 BR BKN048 06/05 Q1023 GRN 12010KT 4500 BR BKN040',
    parsed:
      { type: 'METAR',
        station: 'EHLW',
        time: Time.strptime('151755+0000', '%d%H%M%z'),
        auto: true,
        correction: false,
        wind:   { speed: 11,
                  direction: 110,
                  variable: true,
                  variation: { min: 60, max: 150 },
                  unit: 'KT' },
        cavok: false,
        visibility: { distance: '4000', unit: 'meters' },
        runway_visual_range: nil,
        weather: ['mist'],
        clouds:   [{ type: 'broken',
                     altitude: 4800,
                     cumulonimbus: false,
                     towering_cumulus: false }],
        recent_weather: nil,
        temperature: { temperature: 6, dewpoint: 5 },
        windshear: nil,
        altimeter: { hpa: 1023 },
        non_standard: 'GRN 12010KT 4500 BR BKN040'
      },
    readable: 'EHLW (autostation). Dec 15, 17:55 UTC. Variable (from 60 to 150 degrees) wind of 11KT at 110 degrees. Visibility 4000 meters. Temperature 6 degrees. Dew point 5 degrees. Pressure altitude 1023 hpa. Weather : mist. Broken clouds at 4800 feets. Not parsed : GRN 12010KT 4500 BR BKN040.'
  },

  { raw: 'CYSB 231400Z 30006KT 20SM FEW180 M30/M34 A3038 RMK CI1 CI TR SLP333',
    parsed:
      { type: 'METAR',
        station: 'CYSB',
        time: Time.strptime('231400+0000', '%d%H%M%z'),
        auto: false,
        correction: false,
        wind:   { speed: 6, direction: 300, variable: false, variation: nil, unit: 'KT' },
        cavok: false,
        visibility: { distance: '20', unit: 'SM' },
        runway_visual_range: nil,
        weather: nil,
        clouds:   [{ type: 'few',
                     altitude: 18_000,
                     cumulonimbus: false,
                     towering_cumulus: false }],
        recent_weather: nil,
        temperature: { temperature: -30, dewpoint: -34 },
        windshear: nil,
        altimeter: { hg: 30.38 },
        non_standard: 'RMK CI1 CI TR SLP333'
      },
    readable: 'CYSB. Dec 23, 14:00 UTC. Wind of 6KT at 300 degrees. Visibility 20 SM. Temperature -30 degrees. Dew point -34 degrees. Pressure altitude 30.38 inches of mercury. Few clouds at 18000 feets. Not parsed : RMK CI1 CI TR SLP333.'
  },

  { raw: 'KBIL 162256Z VRB17G27KT 3/4SM FEW070 SCT085 BKN110 M02/M02 A2961',
    parsed:
      {
        type: 'METAR',
        station: 'KBIL',
        time: Time.strptime('162256+0000', '%d%H%M%z'),
        auto: false,
        correction: false,
        wind:   { speed: 17, gust: 27, direction: nil, variable: true, variation: nil, unit: 'KT' },
        cavok: false,
        visibility: { distance: '3/4', unit: 'SM' },
        runway_visual_range: nil,
        weather: nil,
        clouds:   [{ type: 'few',
                     altitude: 7000,
                     cumulonimbus: false,
                     towering_cumulus: false },
                   { type: 'scattered',
                     altitude: 8500,
                     cumulonimbus: false,
                     towering_cumulus: false },
                   { type: 'broken',
                     altitude: 11_000,
                     cumulonimbus: false,
                     towering_cumulus: false }],
        recent_weather: nil,
        temperature: { temperature: -2, dewpoint: -2 },
        windshear: nil,
        altimeter: { hg: 29.61 },
        non_standard: nil
      },
    readable: 'KBIL. Dec 16, 22:56 UTC. Variable wind of 17KT with gusts to 27KT. Visibility 3/4 SM. Temperature -2 degrees. Dew point -2 degrees. Pressure altitude 29.61 inches of mercury. Few clouds at 7000 feets, scattered clouds at 8500 feets, broken clouds at 11000 feets.'
  }

]
