require 'metar_taf'

METAR_EXPECTATIONS = [

  { raw: 'EGGW 091450Z 21013KT CAVOK 10/06 Q1031',
    parsed:
    { type: 'METAR',
      station: 'EGGW',
      time: Time.strptime('091450+0000', '%d%H%M%z'),
      auto: false,
      correction: false,
      wind: { variation: nil, direction: 210, variable: false, speed: 13, unit: 'KT' },
      cavok: true,
      visibility: nil,
      runway_visual_range: nil,
      weather: nil,
      clouds: nil,
      temperature: { temperature: 10, dewpoint: 6 },
      altimeter: { hpa: 1031 },
      recent_weather: nil,
      windshear: nil,
      non_standard: nil
    },
    readable: 'Dec 9, 1450 UTC. Wind of 13 KT ar 210 degrees. Clear sky. Temperature 10 degrees, dew point 6 degrees. Pressure altitude 1031 hPa'
  },

  { raw: 'METAR EFJY 171950Z AUTO CCA 27006KT 220V310 9999 R36/1000V2400FT/U +BLSN VCSH FEW012 SCT015 BKN060 13/12 Q1006 REFZRA WS RWY36',
    parsed:
      { type: 'METAR',
        station: 'EFJY',
        time: Time.strptime('171950+0000', '%d%H%M%z'),
        auto: true,
        correction: 'A',
        wind:   { speed: 6,
                  direction: 270,
                  variable: true,
                  variation: { min: 220, max: 310 },
                  unit: 'KT' },
        cavok: false,
        visibility: { distance: 9999.0, unit: 'meters' },
        runway_visual_range: { runway: '36', direction: nil, minIndicator: nil, minValue: '1000', maxIndicator: nil, maxValue: '2400', unit: 'FT', trend: 'U' },
        weather: ['heavy intensity blowing snow', 'in the vicinity showers'],
        clouds:   [{ type: 'few',
                     altitude: 1200,
                     cumulonimbus: false,
                     towering_cumulus: false },
                   { type: 'scattered',
                     altitude: 1500,
                     cumulonimbus: false,
                     towering_cumulus: false },
                   { type: 'broken',
                     altitude: 6000,
                     cumulonimbus: false,
                     towering_cumulus: false }],
        recent_weather: 'Freezing Rain',
        temperature: { temperature: 13, dewpoint: 12 },
        windshear: 'runway 36',
        altimeter: { hpa: 1006 },
        non_standard: nil
    },
    readable: ''
  },

  { raw: 'SPECI EGGW 151750Z 14012KPH 6000 RA BKN003 OVC004 10/10 Q1014',
    parsed:
      { type: 'SPECI',
        station: 'EGGW',
        time: Time.strptime('151750+0000', '%d%H%M%z'),
        auto: false,
        correction: false,
        wind:   { speed: 12, direction: 140, variable: false, variation: nil, unit: 'KPH' },
        cavok: false,
        visibility: { distance: 6000.0, unit: 'meters' },
        runway_visual_range: nil,
        weather: ['rain'],
        clouds:   [{ type: 'broken',
                     altitude: 300,
                     cumulonimbus: false,
                     towering_cumulus: false },
                   { type: 'overcast',
                     altitude: 400,
                     cumulonimbus: false,
                     towering_cumulus: false }],
        recent_weather: nil,
        temperature: { temperature: 10, dewpoint: 10 },
        windshear: nil,
        altimeter: { hpa: 1014 },
        non_standard: nil
      },
    readable: ''
  },

  { raw: 'EHLW 151755Z AUTO 11011KT 060V150 4000 BR BKN048 06/05 Q1023 GRN 12010KT 4500 BR BKN040',
    parsed:
      { type: 'METAR',
        station: 'EHLW',
        time: Time.strptime('151755+0000', '%d%H%M%z'),
        auto: true,
        correction: false,
        wind:   { speed: 11,
                  direction: 110,
                  variable: true,
                  variation: { min: 60, max: 150 },
                  unit: 'KT' },
        cavok: false,
        visibility: { distance: 4000.0, unit: 'meters' },
        runway_visual_range: nil,
        weather: ['mist'],
        clouds:   [{ type: 'broken',
                     altitude: 4800,
                     cumulonimbus: false,
                     towering_cumulus: false }],
        recent_weather: nil,
        temperature: { temperature: 6, dewpoint: 5 },
        windshear: nil,
        altimeter: { hpa: 1023 },
        non_standard: 'GRN 12010KT 4500 BR BKN040'
      },
    readable: ''
  },

  { raw: 'CYSB 231400Z 30006KT 20SM FEW180 M30/M34 A3038 RMK CI1 CI TR SLP333',
    parsed:
      { type: 'METAR',
        station: 'CYSB',
        time: Time.strptime('231400+0000', '%d%H%M%z'),
        auto: false,
        correction: false,
        wind:   { speed: 6, direction: 300, variable: false, variation: nil, unit: 'KT' },
        cavok: false,
        visibility: { distance: 20.0, unit: 'SM' },
        runway_visual_range: nil,
        weather: nil,
        clouds:   [{ type: 'few',
                     altitude: 18_000,
                     cumulonimbus: false,
                     towering_cumulus: false }],
        recent_weather: nil,
        temperature: { temperature: -30, dewpoint: -34 },
        windshear: nil,
        altimeter: { hg: 30.38 },
        non_standard: 'RMK CI1 CI TR SLP333'
      },
    readable: ''
  },

  { raw: 'KBIL 162256Z VRB17G27KT 3/4SM FEW070 SCT085 BKN110 M02/M02 A2961',
    parsed:
      {
        type: 'METAR',
        station: 'KBIL',
        time: Time.strptime('162256+0000', '%d%H%M%z'),
        auto: false,
        correction: false,
        wind:   { speed: 17, gust: 27, direction: nil, variable: true, variation: nil, unit: 'KT' },
        cavok: false,
        visibility: { distance: 0.75, unit: 'SM' },
        runway_visual_range: nil,
        weather: nil,
        clouds:   [{ type: 'few',
                     altitude: 7000,
                     cumulonimbus: false,
                     towering_cumulus: false },
                   { type: 'scattered',
                     altitude: 8500,
                     cumulonimbus: false,
                     towering_cumulus: false },
                   { type: 'broken',
                     altitude: 11_000,
                     cumulonimbus: false,
                     towering_cumulus: false }],
        recent_weather: nil,
        temperature: { temperature: -2, dewpoint: -2 },
        windshear: nil,
        altimeter: { hg: 29.61 },
        non_standard: nil
      },
    readable: ''
  }

]
